#!/bin/sh

mount -t proc none /proc

pivot() {
 local rw_root work_dir
 rw_root="$1"
 work_dir="$2"
 /bin/mount \
  -o noatime,lowerdir=/,upperdir=${rw_root},workdir=${work_dir} \
  -t overlay "overlayfs:${rw_root}" /mnt
 /usr/sbin/pivot_root /mnt /mnt/rom
}

do_overlay() {
 local overlay_dir="/overlay"
 if [ "$overlay_root" = ram ] ||
  [ -z "$overlay_root" ]; then
  /bin/mount -t tmpfs -o noatime,mode=0755 tmpfs /overlay
 else
  /bin/mount -t ext4 "/dev/$overlay_root" /overlay
 fi
 mkdir -p /overlay/root /overlay/work
 pivot /overlay/root /overlay/work
}

if [ -n "$overlay_root" ] &&
 [ "$overlay_root" != ram ] &&
 [ ! -b "/dev/$overlay_root" ]; then
 echo -n "FATAL: "
 echo "Overlay root given as $overlay_root but /dev/$overlay_root does not exist"
 exit 1
fi

do_overlay

exec /sbin/init $@